### ISSUE TITLE
DSCLOCK.SYS Validation problem for 2 digit months (10, 11, 12)

### ISSUE THREAD

**Issue by grimjacksl** [spark2k06/RTC8088#11]
Installed the nice DSCLOCK.SYS driver on my old IBM PC after putting together one of the RTC8088 ISA cards. It was working fine but then reset the date/time when the month changed from September to October. Debugging the DSCLOCK.ASM it looks like a bcd_to_binary function call is missing after the value is pulled from the CMOS, so for months < 10, the binary and BCD were the same and worked but for October (month 10) the BCD value is 0001 0000 and the binary value is 0000 1010. Adding the bcd_to_binary call appears to fix the issue.

Before: 
   802 00000402 2EA0[2300]              	mov	al,cs:[month+1]
   803 00000406 3C0C                    	        cmp	al,12			; month must be between 1 and 12

After:
   802 00000402 2EA0[2300]              	mov	al,cs:[month+1]
   803 00000406 E874FE                          call bcd_to_binary
   804 00000409 3C0C                    	        cmp	al,12			; month must be between 1 and 12

re-ran NASM on the modified DSCLOCK.ASM file, reinstalled the DSCLOCK.SYS and two-digit months are not causing a validation problem now.

**Comment by spark2k06** [comment]
Fixed.
