### ISSUE TITLE
Update the Hackaday project description - 8088 BIOS information

### ISSUE THREAD

**Issue by skiselev** [spark2k06/RTC8088#2]
The RTC autodetection has been merged to the 8088 BIOS long ago.

Can you please update the following statement: "Until he decides to make it public in your GitHub repository" (I believe it was always public, maybe it wasn't in an "official release") to something like use the latest [8088 BIOS](https://github.com/skiselev/8088_bios) version. Binary images are available [here](https://github.com/skiselev/8088_bios/tree/master/binaries)".

**Comment by spark2k06** [comment]
Sorry, thanks for the heads up because I hardly remembered anymore. Yes, I will do so during the day.

**Comment by spark2k06** [comment]
Done!

https://hackaday.io/project/168972-rtc-isa-8-bits-pcxt
