### ISSUE TITLE
Add jumper to select the I/O address

### ISSUE THREAD

**Issue by skiselev** [spark2k06/RTC8088#3]
Currently the project uses different SPLD bitstreams to select the RTC I/O address.
Therefore, to change the I/O address, it requires reprogramming the SPLD, which is not a viable option for most users.

I recommend two options for modifications to allow configuring the I/O addresses:

1. Simple: Use currently unused pin 19 to select between two addresses. This is a really simple change. It will require adding a jumper and a pull-up resistor on this pin.
2. More complicated: Free up 1-2 more pins. A few options here:
* Don't decode A2, and perhaps even don't decode A3. The I/O port allocation in IBM PC-compatibles is typically done with 0x10/16 addresses increments anyway. Use freed up signals to add switches or jumpers.
* Don't implement the IRQ. I don't think it is being used often, and perhaps not being used at all...

**Comment by spark2k06** [comment]
Good proposals, I take note for a next version.

**Comment by spark2k06** [comment]
With this version we will have 5 bits to play with the address mapping:

![image](https://github.com/spark2k06/RTC8088/assets/3509674/a5c52fcc-3d57-4ec8-8756-008528df3bb6)

![image](https://github.com/spark2k06/RTC8088/assets/3509674/fd53cdd4-4c45-47e2-b9f3-dc74ceb64965)


I will now think about their implementation in the SPLD.

**Comment by spark2k06** [comment]
Thank you for your great contribution @skiselev, I merge your changes.
